spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rita
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true

  security:
    jwt:
      secret-key: DB7A9CF3-4D9B-4526-B3A2-9E1761D8F1B8
      # 1000 * 3600 * 24 * 7
      max-age: 604800000
      orderly-anonymous-inspections:
        - permitted-urls:
            - /**
        - authenticated-urls:
            - /api/v1/**
        - permitted-urls:
            - /*/*/auth/**
            - /*/*/face/**


